INSERT INTO tb_user (name, email, password) VALUES ('Alex', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Bob', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');


INSERT INTO tb_role (authority) VALUES ('ROLE_OPERATOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_ADMIN');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');


INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 3);


INSERT INTO tb_course (name, area) VALUES ('Software Engineering', 'Exact');
INSERT INTO tb_course (name, area) VALUES ('Mechanical Engineering', 'Exact');
INSERT INTO tb_course (name, area) VALUES ('Civil Engineering', 'Exact');
INSERT INTO tb_course (name, area) VALUES ('Production Engineering', 'Exact');
INSERT INTO tb_course (name, area) VALUES ('Energy Engineering', 'Exact');
INSERT INTO tb_course (name, area) VALUES ('Physical Engineering', 'Exact');
INSERT INTO tb_course (name, area) VALUES ('Electrical Engineering', 'Exact');
INSERT INTO tb_course (name, area) VALUES ('Medicine', 'Health');
INSERT INTO tb_course (name, area) VALUES ('Biomedicine', 'Health');
INSERT INTO tb_course (name, area) VALUES ('Veterinary Medicine', 'Health');
INSERT INTO tb_course (name, area) VALUES ('Odontology', 'Health');
INSERT INTO tb_course (name, area) VALUES ('Psychology', 'Health');
INSERT INTO tb_course (name, area) VALUES ('Esthetics', 'Health');
INSERT INTO tb_course (name, area) VALUES ('Physical Education (Bachelor)', 'Health');
INSERT INTO tb_course (name, area) VALUES ('Physical Education (Degree)', 'Health');
INSERT INTO tb_course (name, area) VALUES ('Law', 'Humans');
INSERT INTO tb_course (name, area) VALUES ('Performing Arts', 'Humans');
INSERT INTO tb_course (name, area) VALUES ('Visual Arts', 'Humans');
INSERT INTO tb_course (name, area) VALUES ('Literature', 'Humans');
INSERT INTO tb_course (name, area) VALUES ('Business', 'Humans');
INSERT INTO tb_course (name, area) VALUES ('Design', 'Humans');
INSERT INTO tb_course (name, area) VALUES ('Marketing', 'Humans');
INSERT INTO tb_course (name, area) VALUES ('-', 'Humans');


INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99676-1678', 'https://www.instagram.com/anapaulatubiana/', 'https://www.facebook.com/anapaula.tubiana');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99639-8500', 'https://www.instagram.com/guto_petroli/', 'https://www.facebook.com/augusto.petroli');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99999-9999', 'https://www.instagram.com/damncarla/', 'https://www.facebook.com/carla.dambroz.7');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99990-1999', 'https://www.instagram.com/caroolcarraro/', 'https://www.facebook.com/caroline.carraro.1');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99939-6633', 'https://www.instagram.com/eduardapastorello/', 'https://www.facebook.com/eduarda.pastorello.7');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99175-1270', 'https://www.instagram.com/eduardazt_/', 'https://www.facebook.com/duda.zorzi.79');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)98110-8707', 'https://www.instagram.com/eduardomartinsdesouza/', 'https://www.facebook.com/eduardo.martinsdesouza.90');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)98445-1422', 'https://www.instagram.com/emanuelscaldeira/', 'https://www.facebook.com/emanuel.caldeira.18');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99999-9999', 'https://www.instagram.com/emillyfreitass/', 'https://www.facebook.com/emilly.kjlxtu');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99972-0403', 'https://www.instagram.com/felipe.ranzan/', 'https://www.facebook.com/felipe.ranzan');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99175-7789', 'https://www.instagram.com/f.rizzardo/', 'https://www.facebook.com/felipe.rizzardo.1');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99664-2705', 'https://www.instagram.com/gabilocatelli_/', 'https://www.facebook.com/gabriela.locatelli.980');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99105-4844', 'https://www.instagram.com', 'https://www.facebook.com/gabsferronato');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99618-3259', 'https://www.instagram.com/gabi.mbatisti/', 'https://www.facebook.com/gabrielle.batisti');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99924-6094', 'https://www.instagram.com/giovanni.guidolin/', 'https://www.facebook.com/giovanni.guidolin117');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99999-9999', 'https://www.instagram.com/guiheuseralmeida/', 'https://www.facebook.com/guilherme.almeida.779205');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99943-1583', 'https://www.instagram.com/guilhermebauce/', 'https://www.facebook.com/guilherme.bauce.3');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99974-7432', 'https://www.instagram.com/jonathan.gfra/', 'https://www.facebook.com/jonathan.franceschini.56');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99676-9141', 'https://www.instagram.com/julia_dalla_costa/', 'https://www.facebook.com/julia.dallacosta.7');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99984-2872', 'https://www.instagram.com/juliapertile.vet/', 'https://www.facebook.com/profile.php?id=100010515136823');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99657-0555', 'https://www.instagram.com/lorenzobondan/', 'https://www.facebook.com/loorenzo.bondaan');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99944-6137', 'https://www.instagram.com/lucas.tog40/', 'https://www.facebook.com/lucas.tognon.771');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99651-1057', 'https://www.instagram.com/luiz_bordin/', 'https://www.facebook.com/luizbordin');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99183-3720', 'https://www.instagram.com/luizaconzatti/', 'https://www.facebook.com/luiza.nconzatti');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99980-9189', 'https://www.instagram.com/gava_maicon/', 'https://www.facebook.com/maicon.gava.3');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99999-9999', 'https://www.instagram.com/mauri_baldassarelli/', 'https://www.facebook.com/mauricio.todescatobaldassarelli');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99676-1678', 'https://www.instagram.com/nicolesanson/', 'https://www.facebook.com/nicoletsanson');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99186-9689', 'https://www.instagram.com/rodrigochultz_/', 'https://www.facebook.com');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99168-2015', 'https://www.instagram.com/thomazcantoni/', 'https://www.facebook.com/thomaz.cantoni');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99612-1643', 'https://www.instagram.com/viniciusguidolin/', 'https://www.facebook.com/vini.guido.56');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99999-9999', 'https://www.instagram.com/iuri_engel/', 'https://www.facebook.com');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99999-9999', 'https://www.instagram.com/raphapompermayer/', 'https://www.facebook.com');
INSERT INTO tb_contact (phone, instagram, facebook) VALUES ('tel:+55(54)99999-9999', 'https://www.instagram.com/p/ChQg7UkJObx/', 'https://www.facebook.com/francine.perego');


INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Ana Paula Reginatto Tubiana', 'Ana', 1, 'Porto Alegre', 'High QI and her way of being mad and laugh at the same time', TIMESTAMP WITH TIME ZONE '1999-06-04', false, 'https://i.ibb.co/wdYhvQt/ana.jpg', 'https://i.ibb.co/41BdtDZ/ana-removebg-preview.png', 'This is what you came for', 'Calvin Harris', 'https://upload.wikimedia.org/wikipedia/pt/a/aa/Capa_de_This_Is_What_You_Came_For.png');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Augusto Petroli', 'Guto', 2, 'Bento Gonçalves', 'Always making our meets happier with his tambourine', TIMESTAMP WITH TIME ZONE '1999-06-27', true, 'https://i.ibb.co/k2jL7Sz/augusto.jpg', 'https://i.ibb.co/kBHXy6K/augusto-removebg-preview.png', 'É uma partida de futebol', 'Skank', 'https://upload.wikimedia.org/wikipedia/pt/d/d1/%C3%89_Uma_Partida_de_Futebol.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Carla Dambroz Pelegrin', 'Carla', 3, 'Florianópolis', 'Wonderful creativity and alternative humor sense', TIMESTAMP WITH TIME ZONE '1999-01-19', false, 'https://i.ibb.co/9vQ9D9V/carla.jpg', 'https://i.ibb.co/R02y8Z4/carla-removebg-preview.png', null, null, null);
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Caroline Carraro', 'Carol', 4, 'Porto Alegre', 'Her way to call her friends of falsiane', TIMESTAMP WITH TIME ZONE '1999-11-04', false, 'https://i.ibb.co/km0gqsy/caroline.jpg', 'https://i.ibb.co/4mVh1wZ/caroline-removebg-preview.png', 'Paradise', 'Coldplay', 'https://upload.wikimedia.org/wikipedia/pt/2/22/Coldplay_-_Paradise.JPG');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Eduarda Pastorello', 'Duda', 5, 'Caxias do Sul', 'Always being mad and screaming: SILENCEEEE', TIMESTAMP WITH TIME ZONE '1999-12-13', false, 'https://i.ibb.co/Ny2jZRX/eduarda-pastorello.jpg', 'https://i.ibb.co/PCzJ2WZ/eduarda-p-removebg-preview.png', 'Capsize', 'Frenship', 'https://upload.wikimedia.org/wikipedia/en/b/b6/Capsize_-_Single.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Eduarda Zorzi Trevisan', 'Zorzi', 6, 'Bento Gonçalves', 'Her love for horses', TIMESTAMP WITH TIME ZONE '1999-10-29', true, 'https://i.ibb.co/vxxyF24/eduarda-zorzi.jpg', 'https://i.ibb.co/FYvFrDm/eduarda-z-removebg-preview.png', 'Hear me now', 'Alok', 'https://upload.wikimedia.org/wikipedia/pt/7/7a/Hear_Me_Now_cover.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Eduardo Martins de Souza', 'Souza', 7, 'Bento Gonçalves', 'Good humor sense and black power hair', TIMESTAMP WITH TIME ZONE '1999-04-18', true, 'https://i.ibb.co/yhhbqNB/eduardo.jpg', 'https://i.ibb.co/c1hYWhH/eduardo-removebg-preview.png', 'John Cena´s theme song', 'John Cena', 'https://phantom-marca.unidadeditorial.es/8282d52f4aa22fde9df400211365fbb3/resize/1320/f/jpg/assets/multimedia/imagenes/2023/02/05/16755519728234.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Emanuel Salvador Caldeira', 'Manu', 8, 'Porto Alegre', 'Irony and fascination with scientific experiments', TIMESTAMP WITH TIME ZONE '1999-08-30', false, 'https://i.ibb.co/mGBwsZD/emanuel.jpg', 'https://i.ibb.co/jDzZdpM/emanuel-removebg-preview.png', 'Another brick in the wall', 'Pink Floyd', 'https://i.scdn.co/image/ab67616d0000b2735d48e2f56d691f9a4e4b0bdf');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Emilly Vitória de Oliveira Freitas', 'Emilly', 9, 'Bento Gonçalves', 'Explosive humor sense like a bomb', TIMESTAMP WITH TIME ZONE '1999-03-25', true, 'https://i.ibb.co/YXjL08r/emilly.jpg', 'https://i.ibb.co/bRhRTH8/emilly-removebg-preview.png', 'The greatest', 'Sia', 'https://upload.wikimedia.org/wikipedia/pt/f/f4/Capa_de_The_Greatest.png');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Felipe Molinari Ranzan', 'Ranzan', 10, 'Porto Alegre', 'Also knew as Master Ranzan with his innocence', TIMESTAMP WITH TIME ZONE '1999-01-26', false, 'https://i.ibb.co/WkkWfFH/felipe-ranzan.jpg', 'https://i.ibb.co/QmL27m9/felipe-ranzan-removebg-preview.png', 'Lovers on the sun', 'David Guetta', 'https://akamai.sscdn.co/uploadfile/letras/albuns/2/5/1/0/375821667251736.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Felipe Rizzardo', 'Zardo', 11, 'Bento Gonçalves', 'His way to dont take nothing seriously', TIMESTAMP WITH TIME ZONE '1999-05-15', false, 'https://i.ibb.co/br2vnxV/felipe-rizzardo.jpg', 'https://i.ibb.co/L6c8yY5/felipe-rizzardo-removebg-preview.png', null, null, null);
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Francine de Lima Pérego', 'Francine', 33, 'Bento Gonçalves', 'Our fellow that spend many years with us', TIMESTAMP WITH TIME ZONE '1999-10-31', true, 'https://i.ibb.co/Xsq9CMw/francine.jpg', 'https://i.ibb.co/KLMMzWs/francine-removebg-preview.png', null, null, null);
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Gabriela Andreolla Locatelli', 'Gabi', 12, 'Bento Gonçalves', 'Perfectionist, fascinated for cleaning and dedicated', TIMESTAMP WITH TIME ZONE '1999-03-03', true, 'https://i.ibb.co/zVYZK9q/gabriela-locatelli.jpg', 'https://i.ibb.co/Y2Nd5Kh/gabriela-andreola-removebg-preview.png', 'Scarecrow', 'Alex e Sierra', 'https://akamai.sscdn.co/uploadfile/letras/albuns/6/7/9/7/370281412421873.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Gabriela Ferronato', 'Ferronato', 13, 'Bento Gonçalves', 'Justifiable obsession with Xis Bocão', TIMESTAMP WITH TIME ZONE '1998-12-04', false, 'https://i.ibb.co/QC06Y3M/gabriela-ferronato.jpg', 'https://i.ibb.co/vwBb9BF/gabriela-ferronato-removebg-preview.png', 'Trust nobody', 'Cashmere Cat', 'https://images.genius.com/b687b363f5946a77025d300b83ef9cf0.255x255x1.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Gabrielle Masutti Batisti', 'Batisti', 14, 'Bento Gonçalves', 'Also knew as Frozen, feared by her adversaries when serve on volley', TIMESTAMP WITH TIME ZONE '1999-09-22', true, 'https://i.ibb.co/G9fRsk5/gabrielle-batisti.png', 'https://i.ibb.co/R2mFt48/gabrielle-removebg-preview.png', 'All we know', 'The Chainsmokers', 'https://i.scdn.co/image/ab67616d0000b273ff8d8c5662a96d41433e9ee1');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Giovanni Guidolin', 'Gio', 15, 'Bento Gonçalves', 'Xbox boy', TIMESTAMP WITH TIME ZONE '1999-08-27', true, 'https://i.ibb.co/tPYh0tr/giovanni.jpg', 'https://i.ibb.co/B2GMh6q/gio-removebg-preview.png', 'The animals', 'The house of the rising sun', 'https://akamai.sscdn.co/uploadfile/letras/albuns/7/e/8/9/1190641636642367.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Guilherme Heuser de Almeida', 'Almeida', 16, 'São Paulo', 'For a while, was knew as Santo Antônio, because of his hair', TIMESTAMP WITH TIME ZONE '1999-02-20', false, 'https://i.ibb.co/RS2WjDK/guilherme-almeida.jpg', 'https://i.ibb.co/r3yh66b/guilherme-almeida-removebg-preview.png', 'Sweet Child O´Mine', 'Gun´s and roses', 'https://upload.wikimedia.org/wikipedia/pt/e/e5/Guns_N%27_Roses_-_Sweet_Child_o%27_Mine.jpeg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Guilherme Picoli Bauce', 'Bauce', 17, 'Porto Alegre', 'Our DJ, always with his untouchable hair', TIMESTAMP WITH TIME ZONE '1999-07-01', false, 'https://i.ibb.co/fdZ46vB/guilherme-bauce.jpg', 'https://i.ibb.co/XVCcngJ/guilherme-bauce-removebg-preview.png', 'Hotel Room Service', 'Pitbull', 'https://upload.wikimedia.org/wikipedia/en/4/4a/Pitbull_-_Hotel_Room_Service_%28Single_Cover%29M-E.png');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Iuri Matheus Engel', 'Iuri', 31, 'Pelotas', 'Used to be mad when called by Iurinelson or Yuri Mammoth', TIMESTAMP WITH TIME ZONE '1999-01-01', false, 'https://i.ibb.co/LCtkqd7/iuri.png', 'https://i.ibb.co/WfR2LYM/iuri-removebg-preview.png', null, null, null);
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Jonathan Guidolin Franceschini', 'Johny', 18, 'Bento Gonçalves', 'Hacker skills and looks like the spider man actor', TIMESTAMP WITH TIME ZONE '1999-03-02', false, 'https://i.ibb.co/FJxpDNr/jonathan.jpg', 'https://i.ibb.co/10t0fFs/johny-removebg-preview.png', null, null, null);
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Julia Dalla Costa', 'Julia', 19, 'Porto Alegre', 'Always joked and went back saying HÃÃ. Fear of butterflies', TIMESTAMP WITH TIME ZONE '1999-10-04', false, 'https://i.ibb.co/hmLzWCT/julia-dc.jpg', 'https://i.ibb.co/fNDwFdT/julia-dc-removebg-preview.png', 'Solo Dance', 'Martin Jansen', 'https://i.scdn.co/image/ab67616d00001e02882fe3a4e4b57038ee7db9d9');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Julia Gheno Pertile', 'Pertile', 20, 'Garibaldi', 'Our girl from Garibaldi, also called by piradinha when was mad', TIMESTAMP WITH TIME ZONE '1999-09-21', true, 'https://i.ibb.co/t4QPfb2/julia-pertile.jpg', 'https://i.ibb.co/mB5D54g/julia-pertile-removebg-preview.png', 'Sweet Home Alabama', 'Lynyrd Skynyrd', 'https://upload.wikimedia.org/wikipedia/en/e/e4/Skynyrd-Sweet-Home-Alabama.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Lorenzo Benatti Bondan', 'Lore', 21, 'Bento Gonçalves', 'The head of crime, always with good ideas', TIMESTAMP WITH TIME ZONE '1999-07-17', false, 'https://i.ibb.co/KwJyNfM/lorenzo.jpg', 'https://i.ibb.co/Y0Jw08f/lorenzo-removebg-preview.png', 'Todo mundo gosta de mim', 'Ultraje a rigor', 'https://i.scdn.co/image/ab67616d00001e0271b6a32ba8b82146b8d6b700');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Lucas Fabichaki Tognon', 'Tognon', 22, 'Bento Gonçalves', 'The black sheep of the class', TIMESTAMP WITH TIME ZONE '1999-09-14', false, 'https://i.ibb.co/wQ2b2Dj/lucas.jpg', 'https://i.ibb.co/rsMLtpH/lucas-removebg-preview.png', null, null, null);
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Luiz Eduardo Bordin', 'Bordin', 23, 'Porto Alegre', 'Always making the other ones mad when shaking his legs, or interrupting the teachers saying: I dont understood very well', TIMESTAMP WITH TIME ZONE '1999-08-08', false, 'https://i.ibb.co/Tvdj75b/luiz.jpg', 'https://i.ibb.co/3cxL5jH/luiz-removebg-preview.png', 'Sometimes', 'Miami Horror', 'https://i1.sndcdn.com/artworks-000002407762-3labyu-t500x500.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Luiza Nunes Conzatti', 'Luiza', 24, 'Porto Alegre', 'Often scratched by sleeping in the class, also called of Crackuda', TIMESTAMP WITH TIME ZONE '1999-11-11', false, 'https://i.ibb.co/TLVDDD8/luiza.jpg', 'https://i.ibb.co/x15by4f/luiza-removebg-preview.png', 'Charlie Brown', 'Coldplay', 'https://upload.wikimedia.org/wikipedia/pt/2/2b/Coldplaycharliebrown.jpg');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Maicon Gava', 'Maicon', 25, 'Bento Gonçalves', 'His way of say BOTI and his shave trimmed in Planalto´s Barber Shop', TIMESTAMP WITH TIME ZONE '1999-08-11', false, 'https://i.ibb.co/9q1M576/maicon.jpg', 'https://i.ibb.co/1sF1Pcc/maicon-removebg-preview.png', 'Can´t Hold Us', 'Macklemore', 'https://upload.wikimedia.org/wikipedia/pt/6/65/Capa_de_Can%27t_Hold_Us.png');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Maurício Todescatto Baudassarelli', 'Mauri', 26, 'Bento Gonçalves', 'Also knew as Dennis Pimentinha. At the class, just said PESADO', TIMESTAMP WITH TIME ZONE '1999-06-20', false, 'https://i.ibb.co/LpBGc8v/mauri.jpg', 'https://i.ibb.co/Gd674jk/mauri-removebg-preview.png', null, null, null);
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Nicole Tabaldi Sanson', 'Nicole', 27, 'Bento Gonçalves', 'Sweet way to sneeze', TIMESTAMP WITH TIME ZONE '1999-11-08', true, 'https://i.ibb.co/JQPtyVD/nicole.jpg', 'https://i.ibb.co/bKb99PZ/nicole-removebg-preview.png', 'Faded', 'Alan Walker', 'https://upload.wikimedia.org/wikipedia/pt/f/f6/Capa_de_Faded_%28Alan_Walker%29.png');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Raphaella Gava Pompermayer', 'Rapha', 32, 'São Paulo', 'Official chopp girl with her ainnn', TIMESTAMP WITH TIME ZONE '1999-01-01', false, 'https://i.ibb.co/kG5DWg6/raphaella.png', 'https://i.ibb.co/sq9mFrB/raphaella-removebg-preview.png', null, null, null);
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Rodrigo Chultz', 'Rodrigo', 28, 'Porto Alegre', 'Sings and does parkour in his free time', TIMESTAMP WITH TIME ZONE '1999-03-04', false, 'https://i.ibb.co/3sT8ds7/rodrigo.jpg', 'https://i.ibb.co/52CwwZm/rodrigo-removebg-preview.png', 'Halfway There', 'Big Time Rush', 'https://i.scdn.co/image/ab67616d0000b27350acd1f66ebd5b84630c7129');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Thomaz Cantoni', 'Thomaz', 29, 'Bento Gonçalves', 'The one who will replace Mister M with his magic tricks', TIMESTAMP WITH TIME ZONE '1999-07-19', true, 'https://i.ibb.co/Xb3bPcL/thomaz.jpg', 'https://i.ibb.co/hZKtcCS/thomaz-removebg-preview.png', 'City is Ours', 'Big Time Rush', 'https://i.scdn.co/image/ab67616d0000b27350acd1f66ebd5b84630c7129');
INSERT INTO tb_student (name, nickname, contact_id, location, description, birth_Date, graduated, img_Url, postit_Url, music_Name, music_Author, music_Img_Url) VALUES ('Vinicius Mocelin Guidolin', 'Vini', 30, 'Bento Gonçalves', 'His very funny way to sing VAI TOMA and imitate the Faustão', TIMESTAMP WITH TIME ZONE '2000-12-28', false, 'https://i.ibb.co/n3cyqs8/vini.jpg', 'https://i.ibb.co/hFd2TpL/vini-removebg-preview.png', 'Hold Up', 'Snoop Dogg', 'https://thisis-images.scdn.co/37i9dQZF1DZ06evO4jkBCE-default.jpg');


INSERT INTO tb_student_course (student_id, course_id) VALUES (1, 8);
INSERT INTO tb_student_course (student_id, course_id) VALUES (2, 14);
INSERT INTO tb_student_course (student_id, course_id) VALUES (2, 15);
INSERT INTO tb_student_course (student_id, course_id) VALUES (3, 17);
INSERT INTO tb_student_course (student_id, course_id) VALUES (4, 8);
INSERT INTO tb_student_course (student_id, course_id) VALUES (5, 8);
INSERT INTO tb_student_course (student_id, course_id) VALUES (6, 10);
INSERT INTO tb_student_course (student_id, course_id) VALUES (7, 16);
INSERT INTO tb_student_course (student_id, course_id) VALUES (8, 3);
INSERT INTO tb_student_course (student_id, course_id) VALUES (9, 13);
INSERT INTO tb_student_course (student_id, course_id) VALUES (10, 5);
INSERT INTO tb_student_course (student_id, course_id) VALUES (11, 4);
INSERT INTO tb_student_course (student_id, course_id) VALUES (12, 22);
INSERT INTO tb_student_course (student_id, course_id) VALUES (13, 19);
INSERT INTO tb_student_course (student_id, course_id) VALUES (14, 9);
INSERT INTO tb_student_course (student_id, course_id) VALUES (15, 21);
INSERT INTO tb_student_course (student_id, course_id) VALUES (16, 20);
INSERT INTO tb_student_course (student_id, course_id) VALUES (17, 8);
INSERT INTO tb_student_course (student_id, course_id) VALUES (18, 16);
INSERT INTO tb_student_course (student_id, course_id) VALUES (19, 7);
INSERT INTO tb_student_course (student_id, course_id) VALUES (20, 7);
INSERT INTO tb_student_course (student_id, course_id) VALUES (21, 6);
INSERT INTO tb_student_course (student_id, course_id) VALUES (22, 10);
INSERT INTO tb_student_course (student_id, course_id) VALUES (23, 1);
INSERT INTO tb_student_course (student_id, course_id) VALUES (23, 2);
INSERT INTO tb_student_course (student_id, course_id) VALUES (24, 23);
INSERT INTO tb_student_course (student_id, course_id) VALUES (25, 12);
INSERT INTO tb_student_course (student_id, course_id) VALUES (26, 18);
INSERT INTO tb_student_course (student_id, course_id) VALUES (27, 23);
INSERT INTO tb_student_course (student_id, course_id) VALUES (28, 2);
INSERT INTO tb_student_course (student_id, course_id) VALUES (29, 11);
INSERT INTO tb_student_course (student_id, course_id) VALUES (30, 8);
INSERT INTO tb_student_course (student_id, course_id) VALUES (31, 8);
INSERT INTO tb_student_course (student_id, course_id) VALUES (32, 21);
INSERT INTO tb_student_course (student_id, course_id) VALUES (33, 2);


INSERT INTO tb_review (text, user_id, student_id) VALUES ('The smartest one of our class, after me', 1, 1);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Perfect eyes', 2, 2);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Too much party, boys...', 1, 2);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('I dont remember her entrace sound', 1, 3);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Our choreographer', 2, 5);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('When will our camp be?', 2, 6);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Sometimes in Bento, sometimes in Pelotas and sometimes in Floripa, city of the world!', 1, 7);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Owner of half of the buildings in the city', 1, 8);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('I guess the princess in the post it supposed to be Rapunzel', 2, 9);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Is your degree similar to electrical engineering???', 2, 10);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('The funniest guy I´ve ever meet', 1, 11);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Missed her in the last year', 2, 12);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('She´s my neighbor', 1, 13);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('She´s also my neighbor!', 1, 14);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('My favorite designer! (After Thommy)', 2, 15);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Cuesta in the left sock, threatened, didnt hit, come to the backboard, Peglow took it to cuesta HIT CROSSED EDENÍLSOOOOOOON, 41 YEARSSSS', 1, 16);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('She´s got a smile that it seems to me, Reminds me of childhood memories', 2, 17);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('The best Clash of Clans player of the boys', 2, 18);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('I dont see him since 1985', 2, 19);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('John, the viper', 1, 20);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('I KNOW WHO STOLE YOUR CELL PHONE', 1, 21);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('The ideia of piradinha came from the novel Avenida Brasil, once I was watching it and Carminha was mad, so Tufão asked if she was piradinha... Now you know', 1, 22);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('The creator of all this we are seeing!', 2, 23);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Thank you so much for spending your time doing this for us!', 1, 23);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('How can you remember all these things about us?!', 2, 23);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('The water at 600 meters turns to concrete', 1, 24);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('The mouse eats the snake', 2, 24);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Which will happen first, isabel´s party or the bordin 2.0 rave?', 1, 25);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Do you guys knows `the dungeon´?', 2, 25);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('The original post it were draw by her', 2, 26);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Modricio or Mauríc?', 2, 28);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('She was my classmate in catechesis', 2, 29);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('Send me the Figma from your final paper', 1, 32);
INSERT INTO tb_review (text, user_id, student_id) VALUES ('I never thought that it´d be so simple but I found a way, I found a way', 2, 33);


INSERT INTO tb_diary (year, date, description) VALUES (2016, '15/02', 'Vestidos diferentes no primeiro dia de aula');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '15/02', 'Augusto: tenho certeza que vou conseguir trocar de turma! ~Professor Giuliano dá uma gargalhada ');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '15/02', 'Sonho do Johny: ter uma família');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '17/02', 'Lorenzo entrando na sala do segundo ano com óculos e cabo de vassoura na mão fingindo que é cego');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '17/02', 'Rizzardo tentando empurrar o bordin pra dentro do banheiro feminino');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '22/02','Mulher do pátio: tão fazendo baderna no banheiro? -Rizzardo: AAAAAAAHHHHHHHH');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '22/02', 'Pendurando balões no mastro da bandeira no pátio');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '24/02', 'Tognon: temos que convencer o Lorenzo a jogar LOL, vem ser viado com nós!');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '25/02', '-Miriam: Vai passar na UFRGS esse ano Maicon? -Maicon: Vou tentar né profe... -Miriam: Vai passar na frente!');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '25/02', 'Maicon dizendo que vai trazer arma pra escola e que o pai dele vai ser preso');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '26/02', 'Tá tranquilo tá favorável no recreio e Mariângela recolhendo o celular do Augusto');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '26/02', 'Janta da turma na casa da Julia. Bauce, Souza, Manu e Zorzi bêbados. Souza batendo na porta de vidro e vomitando, Manu dormindo com o copo na mão');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '01/03', 'Tomando um shot de água cada vez que o Edmundo fazia um círculo no quadro');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '01/03', 'Maicon quase apanhando da Pertile');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '02/03', 'Bauce não sabendo o ano que o grêmio ganhou a libertadores');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '05/03', 'Janta do aniver do rodrigo no bauce. Souza cagando, ranzan botando só um pouquinho de vodka no copo pra não ficar bêbado e conversa do Zardo com a mina dizendo que era pra ela mandar nudes logo que ele tava de pau duro');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '07/03', '~bola de gude passa no chão~ Emanuel: virou monobola Maicon?');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '09/03', 'Maicon deitado no chão fingindo que tava passando mal enquanto abriam a galinha');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '19/03', 'Festa de 15 da fefa, chegando tchucos, rizzardo dando pt');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '22/03', 'Lorenzo um período inteiro na sala do segundo ano na aula do Edmundo');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '23/03', 'Miriam: Maicon, teu celular é verde cara...');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '28/03', 'Maicon: Roubei o colete da escola. -Gio: Ladrão');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '28/03', 'Faltas: o superman morre :(');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '11/04', 'Rodo na janela');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '11/04', 'Maicon fazendo magia negra e mauri acordando com um espasmo');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '13/04', 'os mlk é liso no projetor da sala antes da aula');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '13/04', 'Miriam: ainda bem que é rascunho isso aí né Maicon...');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '19/04', 'Lorenzo e Augusto zoando Maicon por estar fazendo migue no joelho');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '20/04', 'Lorenzo colando foto sua na classe');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '20/04', 'Maicon com o brinquedinho da baleia');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '20/04', 'Thomaz desligando o projetor com o app de controle universal');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '20/04', 'Lorenzo dizendo que Tognon não dorme e Tiago se estourando de rir');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '01/05', 'Viral de maio: Quero café');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '02/05', 'Barrados na entrada da escola com coberta, pijama e roupão');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '02/05', 'Bordin esticando os braços até a metade com medo de ter falado merda');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '02/05', 'Lisi: pq o médico dá remédio de 5 em 5 horas pra tomar? -Tognon: pra não ter que acordar de noite pra tomar');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '03/05', 'Tognon colocando as mãos nos peitos da ana no recreio');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '09/05', 'Fones de ouvido no recreio desconectados do celular');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '09/05', 'Miriam matando os mamonas assassinas');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '11/05', 'Pastorello possuída');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '12/05', 'Lore escrevendo grude gostoso nos comentários da transmissão ao vivo que tava passando no projetor da sala');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '12/05', 'Brincadeira do não pode falar -tipo-, toda a turma');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '14/05', 'Portas abertas da UFRGS: irmã se perdendo, camisinhas voando, quebrando ônibus, pandeiro');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '17/05', 'Inventando que o gio tinha roubado um mercado');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '23/05', 'Zardo: tá frio né Tognon?');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '23/05', 'Desenrolando fio pela sala, pendurando macacos no ventilador, jogando bola na janela, tognon de armadura');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '23/05', 'Lorenzo tendo que sair da sala por não conseguir parar de rir');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '24/05', 'Lorenzo desligando a luz da sala do 9° ano');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '25/05', 'Pódio no mural pela brincadeira do não pode falar tipo: ganharam Nicole, Emilly e Johny');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '25/05', 'Tiago assobiando enquanto Tognon falava');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '25/05', 'Miriam recolhendo OS DOIS celulares do Maicon');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '25/05', 'Isabel manda Gio se cuidar quando ele enfia a mão no cu');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '29/05', 'Ensaio na casa do Bauce, Luiza se espremendo pra passar pela porta, chega o ranzan e simplesmente empurra a porta pra abrir mais');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '31/05', 'Não podendo falar o nome da Raphaella');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '01/06', 'Entrega dos moletons');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '03/06', 'Café no Rodrigo, torta vencida, Maicon peidando no elevador');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '04/06', 'Festa junina, trabalhando nas vendas e ganhando na dança');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '06/06', 'Luiza pedindo se Guilherme era o nome do irmão do Bauce');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '08/06', 'Sentados nas cadeiras do lado de fora da sala');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '08/06', '~Raphaella vai embora~ Miriam: alguém vai junto? -Tognon: Bauce. -Miriam: E o giovanni vai junto!');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '09/06', 'Zardo espalhando mumu pelo banheiro (((simplesmente a vez que eu mais ri na minha vida kkkk)))');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '10/06', 'Deixando um baú no meio do pátio e deixando as crianças curiosas');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '11/06', 'Vestibular da UNISINOS: escrevendo número do manu atrás da porta do banheiro, lore ligando pro bauce durante a prova e se ferrando');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '14/06', 'Início da brincadeira de Detetive');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '15/06', 'Visita ao cenecista');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '16/06', 'Fim da 1ª brincadeira de detetive. Lorenzo descobre que Carla era a assassina');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '17/06', 'Cinema invocação do mal 2, ana paula gritando');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '22/06', 'Piadas com a Isabel dizendo pra amiga PÓ PARÁ');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '23/06', 'Trocando as placas com as metas de salas');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '26/06', 'Vestibular da UCS: Gio discutindo com um gremista aleatório na fila');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '27/06', 'Aniversário do augusto, zoando ele por causa do `muitos boys´');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '03/07', 'Bauce não sabendo que coração de galinha era LITERALMENTE coração de galinha');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '08/07', 'Maicon pedindo pro professor giuliano lançar só mais uma bola pra ele. professor lança, maicon rompe os ligamentos do joelho e todos acham que é migué');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '11/07', 'Bobinho com Maicon manco');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '12/07', 'No dia seguinte -> Augusto aparece manco');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '16/07', 'Janta no augusto com zardo inventando história');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '03/08', 'Desenhando um pinto na cara da Luiza enquanto ela dormia');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '04/08', 'MUITA gente jogando pokemon go dentro do banheiro e tendo que esconder o celular na hora de sair');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '08/08', 'Almeida chamando a Kely de delícia');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '09/08', 'Empurrando o rodrigo pra fora do banco na palesta');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '15/08', 'Amoeba na escola, jogam no teto e ela cai bem na hora que a Vivi entra na sala');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '15/08', 'Bauce e rodrigo contando verdades um sobre o outro');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '19/08', 'Lorenzo estourando balão no meio do provão');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '23/08', 'Lorenzo pendurando avião no teto');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '24/08', 'Viagem pra SP');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '29/08', 'Rodrigo: Sou o único macho aqui. -Vini: aham, bem macho...');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '30/08', 'criança prendendo a cabeça na cerca no recreio');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '01/09', 'Escondendo a mochila da pastorello na portinha da biblioteca');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '02/09', 'Marchando na rua e cantando a música do Maicon');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '04/09', 'Vôlei da turma');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '05/09', 'Zardo chutando a bola pra fora da escola de propósito');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '05/09', 'Imitando a Raphaella com ´aiin´ e a Julia com ´ããã´');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '14/09', 'Chegada das camisetas, choradeira no lanche da turma');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '14/09', 'Fugindo da aula e fazendo cartazes escondidos. Rosângela aparece e não acredita no que vê');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '15/09', 'Interséries: vestidos diferentes e gritando ai cada vez que alguém sacava');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '23/09', 'Almoço na escola, foto no cristo');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '01/10', 'Rizzardo inventando que tinha encontrado o augusto no centro e a mãe desmascarando ele depois');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '11/10', 'Dia das crianças: Cabelos pintados');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '18/10', 'Zoando o maicon por causa do barbeiro que cobra em cu');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '21/10', 'Zardo e Lore indo de mãos dadas até uma guria do funda pro zardo dizer que era gay');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '22/10', 'Janta da turma no bauce: souza projeto X, beer pong');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '24/10', 'Pertile e Zorzi ajudam Lorenzo a tentar andar de bicicleta');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '25/10', 'Zardo dizendo que tira a barba com cera');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '26/10', 'Johny acertando bolinha de papel na cara da professora de inglês');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '27/10', 'CJmarcao@gmail.com');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '28/10', 'Turma escondida na educ física, alguns ficando até o final e passando trote pra professora mandando a bruna descer pra ir embora');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '09/11', 'Tognon: O rato come a cobra. -Thomaz: e a mulher come o homem');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '21/11', 'Manequim Challenge');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '23/11', 'Lorenzo e bauce dizendo que o ranzan ia chegar e pedir de quem a gente tava falando e ele chegou e pediu');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '23/11', 'FOTOS NO MORRO DA ANTENA: MELHOR DIA DO ANO');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '24/11', 'Escondendo champanhe na mochila do rizzardo e estourando depois da aula');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '25/11', 'Retiro: champanhe da turma, todos chorando com as cartas, gio ficando pra trás e ônibus tendo que voltar pra pegar ele');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '26/11', 'Almoço no caça: amigo secreto, guerra de água, zardo baixando as calças do johny');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '27/11', 'Redação da ucs: mulher roubando lápis das classes e gio sentando onde tava sem');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '29/11', 'Esconde esconde da turma, lorenzo quebrando o pato de porcelana e vídeos Ned pra formatura');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '30/11', 'Último dia de aula: vestidos com profissões/times, escondidos pra bater foto, fugindo da vivi: todos desesperados porque a porta estava fechada e a luiza simplesmente abre (estava destrancada)');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '01/12', 'Voltando ao colégio, pegando troféu e bonés de 1990, entrando na casa das irmãs');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '08/12', 'Formatura: Chegando de kombi, música da Pertile falhando, jogando bordin e emanuel pro alto, coração não é tão simples quanto pensa no final');
INSERT INTO tb_diary (year, date, description) VALUES (2016, '19/12', 'Almoço no sítio do augusto');


INSERT INTO tb_diary (year, date, description) VALUES (2015, '18/02', 'Guris fingindo que haviam trocado de turma');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '23/02', 'Rodrigo: E essa sugeira aí Gio? -Gio: Ferri né...');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '24/02', 'Rodrigo: Tinha que ser o Aguero, aquele gostoso');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '02/03', 'Cartaz onde o gio senta: `vendo droga e maconha´');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '08/03', 'Ranzan dando spolier de the walking dead pro bauce, que fica puto');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '09/03', 'Tognon: acho que tô com cólica');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '11/03', 'Rizzardo: Giovanniii, Giovanniii ~barulho com a boca');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '12/03', 'Rizzardo admite que toma 3 banhos por dia e Rodrigo fica indignado');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '13/03', '~Algo some~ Turma: procura na mochila do Maicon');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '16/03', 'Rodrigo pinta a tampa do marca texto, bauce arrasta com o pé e pinta todo o tênis');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '16/03', 'Professora: quem pegou o estojo do Luiz? -Maicon incrimina Iuri, que fica todo vermelho e tem que devolver o estojo que o maicon tinha roubado');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '18/03', 'Bordin inspirado batendo na mesa enquanto passava a música da revolução francesa');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '25/03', 'Bordin: o que é aquela cenourinha da babosa, que eu ficava brincando quando era menor? -Isabel: É a parte reprodutiva da planta.');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '25/03', '~Professora explicando matéria~ Ranzan: quanto é 15x15???');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '31/03', 'Rodrigo é pego no flagra tirando foto da bunda das gurias');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '31/03', 'Emanuel dedura que Rodrigo estava tirando foto das bundas');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '31/03', 'Altemir diz que vai mostrar um vídeo no projetor e sem querer abre um vídeo com uma mulher semi nua');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '08/04', 'Miriam: pra que isso aí Giovanni? -Gio: Ferri pediu né...');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '13/04', 'Rizzardo: vamo comemora o dia do beijo junto? -Julia DC: não.');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '13/04', 'Rizzardo agarra Francine por trás e tenta dar um beijo');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '14/04', 'Altemir: Tognon deveria ser mandado para uma ilha');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '24/04', 'Silmara: vou devolver a A2 depois. -Ana Paula: tu não vai mais devolver a A2? ~Silmara fica encarando sem falar nada');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '29/04', 'Após escrever `Avalhiativa´ no web giz, Silmara faz tempestade em copo d´agua e diz: EU SEI ESCREVER AVALIATIVA! ~Pegou o giz e escreveu `Aliativa´.');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '29/04', 'Samantha: Lucas, pensa...');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '29/04', 'Dani: Tognon, sim ou não??? -Tognon: mais ou menos');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '29/04', 'Trabalho sociologia, grupos sociais');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '06/05', 'Lorenzo e rizzardo com piadas sobre a francine ter se derrubado café');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '06/05', 'Gio passa a mão na bunda do Emanuel e diz: gostou né?');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '07/05', 'Maicon manda áudio puxando catarro no grupo errado');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '07/05', 'Luiza gabaritando todas as provas, Lorenzo esfrega na cara dos outros pq sempre disse que ela era inteligente e Rodrigo diz que sabia que ele ia falar isso');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '15/05', 'Lorenzo e Rizzardo competindo pra ver quem comia mais pizza, rizzardo trapaceando e riscando muitas fatias a mais');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '25/05', 'Início da brincadeira `Ooo viado´');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '10/06', 'Isabel mandando o rizzardo dizer que ele era bambi mesmo');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '22/06', 'Zorzi: quem roubou as pilhas da minha calculadora? ~Turma olha pro Gio');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '28/06', 'Rizzardo bêbado na aula cantando malandro é malandro e mané é mané');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '04/07', 'Rizzardo ligando pro johny pra pedir mago');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '08/07', 'Prof: tirar 90 em vini. -Mauri: trintão.');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '13/08', 'Rizzardo comendo a classe');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '13/08', 'Tognon tico duro');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '24/08', 'Rizzardo brincando com a mola');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '24/08', 'Jogando tang e água no chão, parecia mijo');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '24/08', 'Rizzardo não lava a mão após sair do banheiro e cumprimenta 120 pessoas no recreio');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '25/08', 'Ranzan racista');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '26/08', 'Celular do Tognon toca no meio da aula, todo mundo grita e olha pra ele, tognon grita também e finge que não é o dele');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '28/08', 'Bordin pendurando tênis do rizzardo na janela do ginásio');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '01/09', 'Tognon encoxador');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '14/09', 'Rizzardo tem que trocar de lugar por causa de lorenzo e rodrigo. -Rodrigo: é engraçado porque ele é gordo');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '15/09', 'Andando de bichinho no shopping de POA na viagem da turma');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '21/09', 'Início da semana literária, turma de cosplays de filmes');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '21/09', 'Maicon maleiro');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '23/09', 'Miriam: Rizzardo, vou te convidar pra vir lá em casa sábado!');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '24/09', 'Isabel: eu sou mais bonita que o Emanuel. -Rizzardo: não...');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '05/10', 'Rizzardo jogando água nas costas do vini');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '07/10', 'Rizzardo levando amoeba pra aula');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '14/10', 'Rizzardo cantando faz quadradinho de oito atrás da Duccatti');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '19/10', 'Bosta no chão do banheiro masculino');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '20/10', 'Trabalho funk ostentação');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '21/10', 'Avacalhando com a pesquisa do 3° ano e a Vivi vindo xingar a gente');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '21/10', 'Rizzardo imitando boquete pro Bauce rir enquanto ele falava com a Dani');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '04/11', 'Rodrigo gaguejando');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '06/11', 'Johny escrevendo o próprio sobrenome errado no trabalho de educ física');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '10/11', 'Tá pirada Pertile?');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '11/11', 'Luiza Ranzi triste pq o vô morreu. -Ranzan: Bah, que clima é esse? Parece até que morreu alguém');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '11/11', 'Trabalho de bio do bauce rabiscado');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '16/11', 'Johny não lavando a mão depois de sair do banheiro');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '18/11', 'Devolvendo a sujeira pra outra turma');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '23/11', 'Ranzan cortando o cabelo do Rodrigo e com a tesoura na mão dizendo que não cortou');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '25/11', 'Rodrigo zerando atividade avaliativa de química');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '30/11', 'Texto zumbis, português');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '01/12', 'Altemir se despedindo, dizendo que tudo valeu a pena... -Ranzan: Ah, mas tem ano que vem ainda');
INSERT INTO tb_diary (year, date, description) VALUES (2015, '07/12', 'Último dia de aula, fefa intrusa');


INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('18/02', 'First day', 'Where we back to school with different cloethes and was the begin of the best year of the school time', 'https://i.ibb.co/Rb6NSX3/primeirodia.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('09/03', 'Scientific experiment', 'Where we opened an chicken and some students got bad (and other ones pretended to been bad)', 'https://i.ibb.co/2Y5D6s4/galinha.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('19/03', 'Choose of the paranymph of the class', 'Isabel was choosed as the paranymph of our class', 'https://i.ibb.co/XLPt193/paraninfa.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('04/06', 'Dance competition', 'A lot of dedication and training brought the result and we were the champions!', 'https://i.ibb.co/yftmK2m/danca.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('24/08', 'Trip to São Paulo', 'The class spend five days in the biggest city of the country and were present in shows like Altas Horas', 'https://i.ibb.co/kQJyhRj/saopaulo.png');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('14/09', 'Arrival of t-shirts', 'A lot of crying and hugs have marked this day, followed by running away from the classroom and getting hide in the school', 'https://i.ibb.co/3djdHt5/camisetas.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('02/10', 'Awarding the medals of the school games', 'The class got a participation medal, wasn´t the best year in therms of sports', 'https://i.ibb.co/RH7ZhLg/medalha.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('11/10', 'Children´s day', 'Until then, the only time they let us dress up with different costumes and dye our hair', 'https://i.ibb.co/9H2Kc8Q/diadascriancas.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('23/11', 'Photos day', 'We went to Morro da Antena to take our photos and it was one of the best days in the year', 'https://i.ibb.co/GtLcbdM/fotos.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('25/11', 'Day of retreat', 'An other day marked by a lot of crying, with the cards and gifts from our parents! And also, one day in the middle of the nature with a great tranquility', 'https://i.ibb.co/PtfwyGd/retiro.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('26/11', 'Hunting and fishing', 'In the rictim of the end of the year, we did a barbecue, a secret friend and an water war!', 'https://i.ibb.co/7ry2tRx/caca.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('30/11', 'The last day in the school', 'The end of our journey, and also, a new begin in our lives, with the sensation that everything worth it!', 'https://i.ibb.co/hHcqpyQ/ultimodiaaula.jpg');
INSERT INTO tb_moment (date, title, description, img_Url) VALUES ('08/12', 'The prom night', 'Our celebration night, with a lot of dance, music and unusual entrances!', 'https://i.ibb.co/2hPL3Rn/formatura.jpg');